name       : kdeclarative
version    : 5.28.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.28/kdeclarative-5.28.0.tar.xz : b67253d2d7bae15fd385c43716301ac82e420f1d776afe1b748fc756f570ebbc
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Integration of QML and KDE work spaces
description: |
    KDeclarative provides integration of QML and KDE work spaces. It's comprises two parts: a library used by the C++ part of your application to intergrate QML with KDE Frameworks specific features, and a series of QML imports that offer bindings to some of the Frameworks.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpackage-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kpackage-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
