name       : kdeclarative
version    : 5.55.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kdeclarative-5.55.0.tar.xz : aa51a98e66dcfeb08d26cc79b230fac3eac9235a5d3dee08805cf964f3a17210
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of QML and KDE work spaces
description: |
    KDeclarative provides integration of QML and KDE work spaces. It's comprises two parts: a library used by the C++ part of your application to intergrate QML with KDE Frameworks specific features, and a series of QML imports that offer bindings to some of the Frameworks.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpackage-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - kconfig-devel
        - kpackage-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
