name       : kdeclarative
version    : 5.76.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kdeclarative-5.76.0.tar.xz : 3dfaa271a97be48e72d5fff0dd3c3c1995be3b9e7d0451b197b79418d76c4ce3
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Integration of QML and KDE work spaces
description: |
    KDeclarative provides integration of QML and KDE work spaces. It's comprises two parts: a library used by the C++ part of your application to intergrate QML with KDE Frameworks specific features, and a series of QML imports that offer bindings to some of the Frameworks.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kpackage-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - kconfig-devel
        - kpackage-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
