name       : kdeclarative
version    : 5.71.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kdeclarative-5.71.0.tar.xz : ace0e52f561a9cfba1de4b77144a0a68037a1229530fb39070dc837da80ac8f8
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Integration of QML and KDE work spaces
description: |
    KDeclarative provides integration of QML and KDE work spaces. It's comprises two parts: a library used by the C++ part of your application to intergrate QML with KDE Frameworks specific features, and a series of QML imports that offer bindings to some of the Frameworks.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpackage-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - kconfig-devel
        - kpackage-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
