name       : kdeclarative
version    : 5.93.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/kdeclarative-5.93.0.tar.xz : 08a945c793aa8d89d87c42d29c9c11e7c28c47916ae728369ab478892d325067
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
summary    : Integration of QML and KDE work spaces
description: |
    KDeclarative provides integration of QML and KDE work spaces. It's comprises two parts: a library used by the C++ part of your application to intergrate QML with KDE Frameworks specific features, and a series of QML imports that offer bindings to some of the Frameworks.
optimize   : lto
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(Qt5Quick)
    - pkgconfig(x11)
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kpackage-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - kpackage-devel
        - qt5-declarative-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
