name       : kdeclarative
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/kdeclarative-5.39.0.tar.xz : f734913d40d94eafabf7d5a090c50a5e8d1caa597aabdf2eab5862f39db71cd1
license    : LGPL-2.1
component  : programming
summary    : Integration of QML and KDE work spaces
description: |
    KDeclarative provides integration of QML and KDE work spaces. It's comprises two parts: a library used by the C++ part of your application to intergrate QML with KDE Frameworks specific features, and a series of QML imports that offer bindings to some of the Frameworks.
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpackage-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - kconfig-devel
        - kpackage-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
